apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/__GHCR_ORG__/__APP_NAME__
    newName: ghcr.io/__GHCR_ORG__/__APP_NAME__
    newTag: latest

patches:
  - path: ingress-patch.yaml
