apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __APP_NAME__-data
  labels:
    app.kubernetes.io/name: __APP_NAME__
    app.kubernetes.io/part-of: __APP_NAME__
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
