# Cluster master with optional Kubeflow
# Usage: ./setup.sh --profile cluster-master [--gpu] [--enable-kubeflow]

ROLE=cluster-master
DO_CORE=1
DO_DOCKER=1
DO_PYTHON=0
DO_SERVICES=1
DO_SWAP=1
DO_SSH=1
DO_CLUSTER=1
DO_NVIDIA=0

SWAP_SIZE=64G
METALLB_IP_RANGE=10.64.140.43-10.64.140.49
