apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/__GHCR_ORG__/__APP_NAME__
    newName: __APP_NAME__-app
    newTag: local

patches:
  - path: delete-ingress.yaml
  - path: deployment-patch.yaml
