version: '3'

services:
  devpi:
    image: python:3.9-slim
    container_name: devpi-server
    command: >
      bash -c "apt-get update && apt-get install -y curl &&
               pip install devpi-server &&
               if [ ! -d /data/.nodeinfo ]; then devpi-init --serverdir /data; fi &&
               devpi-server --host 0.0.0.0 --port 3141 --serverdir /data"
    ports:
      - "3141:3141"
    volumes:
      - devpi-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3141"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    #restart: unless-stopped

  devpi-init:
    image: python:3.9-slim
    container_name: devpi-init
    build:
      context: .
      dockerfile: Dockerfile.init
    command: >
      bash -c "apt-get update && apt-get install -y curl &&
               bash /data/init_cmds.sh"
    depends_on:
      devpi:
        condition: service_healthy

    #restart: unless-stopped

volumes:
  devpi-data: